### ISSUE TITLE
Cleanup of the repository

### ISSUE THREAD

**Issue by skyluc** [sterglee/scalalab#1]
Hi there.

I had a quick at your project because it was posted on reddit/scala. I have not looked at the code to juge the quality of the library, but I see a few problems with the project itself. Fixing them will make other people more likely to look in depth at your project:
- specify a licence for your code. Without the licence information, nobody can use, read, contribute to your project. If you indent it to be open source, the Apache 2.0 licence is a good basic licence.
- don't put everything in `monospace` in your README.md. It makes it less readable. Use this style only for code related text blocks.
- don't put all your jars and libraries in `/lib`. Git is not made to store big binary files. It will make your git repository hard to use in the future when you add and replace libraries. You have an sbt build file, use it to define the dependencies. It will also make it simpler for other to integrate your library in their application.
  One thing, it is not because you remove the files that they are removed from the git repository. Git keep trace of all the files which have been part of the repository at some point. You have one commit. It would make more sense to me to recreate a blank repository on your machine, copy over only what is really needed, then push force this new 'version' in the github repo.
- not sure what in the usage of the content in the `help` folder. Your could just have links to the pdf in a README file, instead of adding more data to your repository. If you want to provide documentation, you can use github wiki, or github pages to get a simple website.
- 'normalize' your packages. In the JVM world, your packages should look like `org.sterglee.scalalab.something`. It is to avoid name collision with other projects.
- put `.DS_Store` in the `.gitignore`.

I'm sure they are a few more minor points, but the list is long enough :smile: .

**Comment by oyvindberg** [comment]
I'll add the following (also coming from reddit) :
- put example code and an overview of functionality in the readme
- some quick start info would be nice
- dont check in project files

This looks like it could be awesome, but it's difficult to get an understanding of what is actually provided. Keep up the good work! :)
