### ISSUE TITLE
Request: License File 

### ISSUE THREAD

**Issue by ekohlwey** [sterglee/scalalab#2]
Hello! This work is extremely interesting. Would you mind placing a license file in the repository so it is clear how this code may be used?

Thank you!

**Comment by sterglee** [comment]
Hello! 
I used MIT License for ScalaLab

Best Regards

**Comment by ekohlwey** [comment]
Thanks for the info- that's a great license. Can you point to where your docs are for this? A lot of companies now require a LICENSE.txt file to be able to consume a library in a company project (even if it's exploratory or "for fun")- if you could add one of these it would be most helpful.

**Comment by sterg67** [comment]
I have the LICENSE.md file at the root directory of the project. I'm not sure but I think this is the relevant one.

**Comment by ekohlwey** [comment]
That's it! Thank you
